<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_OR_921004_Timesheet_Valid_Data_Submit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a8ea9326-0074-4ddd-8e3c-234f4ad09d96</testSuiteGuid>
   <testCaseLink>
      <guid>8f1d8c1e-3eca-4d3b-abfb-27ac0078b8fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OR_920001_Employee_Time_Module/OR_920002_Employee_Timesheet/TC_OR_920003_Timesheet_With_Valid_and_Required_Field</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7c8c1f41-ed14-441b-82c7-0855152e3b90</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-2</value>
         </iterationEntity>
         <testDataId>Data Files/Employee_Onboarding/Employee_Date</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7c8c1f41-ed14-441b-82c7-0855152e3b90</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UserName</value>
         <variableId>1aa41f16-a87a-446d-ac58-828f80bfaaf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7c8c1f41-ed14-441b-82c7-0855152e3b90</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>986146b1-d676-4a3a-9ec1-017e9b01ff20</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
